site_name: Jahresbericht IFP STZ 2023 - 2024
site_url: https://github.com/ifpstz/Jahresbericht-2023-2024/

theme:
  name: material
  custom_dir: overrides  # Eigene Anpassungen aktivieren
  language: de

  # Navigation
  features:
    - navigation.instant
#    - navigation.tabs
    - navigation.sections
    - navigation.path
    - navigation.indexes
    - navigation.top
    - navigation.footer # footer

  # Berliner Logo
  logo: assets/logo/B_Logo_Baer_PW_4C.png

  # Heller & dunkler Modus
  palette:
    - scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-night
        name: Dunkelmodus aktivieren
    - scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-sunny
        name: Hellmodus aktivieren

  # Schriftarten auf Berlin Type umstellen
  font:
    text: "Berlin Type"
    code: "Fira Code"

  # Social Links
  extra:
    social:
      - icon: fontawesome/brands/github
        link: https://github.com/ifpstz/Jahresbericht-2023-2024

# Fußnoten
markdown_extensions:
  - footnotes
  - attr_list
  - md_in_html

# Plugins
plugins:
    - search
    - pandoc:
        combined: true
        output_path: pdf/Jahresbericht-2023-2024.pdf

# Eigene Styles
extra_css:
  - styles/berlin.css
