site_name: Jahresbericht IFP STZ 2023 - 2024
site_url: https://github.com/ifpstz/Jahresbericht-2023-2024/

theme:
  name: material
  custom_dir: overrides  # Eigene Anpassungen aktivieren
  language: de

  # Navigation
  features:
    - navigation.instant
#    - navigation.tabs
    - navigation.sections
    - navigation.path
    - navigation.indexes
    - navigation.top
    - navigation.footer # footer
#    - toc.integrate # Inhaltsverzeichnis

  # Berliner Logo
  logo: assets/logo/B_Logo_Baer_PW_4C.png

  # Heller & dunkler Modus
  palette:
    - scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-night
        name: Dunkelmodus aktivieren
    - scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-sunny
        name: Hellmodus aktivieren

  # Schriftarten auf Berlin Type umstellen
  font:
    text: "Berlin Type"
    code: "Fira Code"

  # Social Links
  extra:
    social:
      - icon: fontawesome/brands/github
        link: https://github.com/ifpstz/Jahresbericht-2023-2024

# Fußnoten
markdown_extensions:
  - footnotes
  - attr_list
  - md_in_html

# Plugins
plugins:
    - search
    - blog
    - to-pdf:
        author: SenASGIVA
        copyright: Copyright © SenASGIVA 2025
        custom_template_path: docs/styles/pdf.css
        output_path: Jahresbericht.pdf
#        cover_title: Title for the Cover Page
        cover_subtitle: Infrastrukturförderprogramm Stadtteilzentren
        cover_logo: docs/assets/images/hero.jpg
        back_cover: false
        toc_title: "Inhaltsverzeichnis"
        toc_level: 3
        ordered_chapter_level: 0

# Eigene Styles
extra_css:
  - styles/berlin.css
  - styles/pdf.css
